[default]
TOKEN_URL = 'https://accounts.spotify.com/api/token'
REDIRECT_URI = 'http://localhost:5000/callback'
AUTHORIZE_URL = 'https://accounts.spotify.com/authorize'
TRACKS_URL = 'https://api.spotify.com/v1/me/tracks?market=BR'
TRACKS_URL_DELETE = 'https://api.spotify.com/v1/me/tracks'
FLASK_DEBUG = true
EXTENSIONS = [
    'blueprints:init_app'
]